tools:
  php_mess_detector: true
  php_code_sniffer: true
  sensiolabs_security_checker: true
  php_pdepend: true
  php_loc:
    enabled: true
    excluded_dirs: [vendor, tests]
filter:
  excluded_paths:
    - 'tests/*'
build:
  nodes:
    package-tests:
      environment:
        php:
          version: 7.2
      tests:
        override:
          - command: phpunit --coverage-clover=package-coverage-file
            coverage:
              file: package-coverage-file
              format: php-clover